//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonetarWin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S.C. Global Biz S.R.L.")]
        public string BranchName {
            get {
                return ((string)(this["BranchName"]));
            }
            set {
                this["BranchName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BranchAddres {
            get {
                return ((string)(this["BranchAddres"]));
            }
            set {
                this["BranchAddres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Program destinat folosirii EXCLUSIVE în interiorul firmei Global Biz SRL. Utiliza" +
            "rea neautorizată este strict interzisă și va fi sancționată conform legislației " +
            "în vigoare.")]
        public string WarnMsg {
            get {
                return ((string)(this["WarnMsg"]));
            }
            set {
                this["WarnMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfCurrency xmlns:xsi=\"http://www.w" +
            "3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  " +
            "<Currency>\r\n    <Name>LEI</Name>\r\n    <Description>LEI - Leu românesc</Descripti" +
            "on>\r\n    <DenomAmounts>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>500 LEI" +
            "</DenomName>\r\n        <DenomValue>500</DenomValue>\r\n      </CurrencyDenomAmount>" +
            "\r\n      <CurrencyDenomAmount>\r\n        <DenomName>200 LEI</DenomName>\r\n        <" +
            "DenomValue>200</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomA" +
            "mount>\r\n        <DenomName>100 LEI</DenomName>\r\n        <DenomValue>100</DenomVa" +
            "lue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomN" +
            "ame>50 LEI</DenomName>\r\n        <DenomValue>50</DenomValue>\r\n      </CurrencyDen" +
            "omAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>10 LEI</DenomName>\r\n " +
            "       <DenomValue>10</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <Currenc" +
            "yDenomAmount>\r\n        <DenomName>5 LEI</DenomName>\r\n        <DenomValue>5</Deno" +
            "mValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <Den" +
            "omName>1 LEI</DenomName>\r\n        <DenomValue>1</DenomValue>\r\n      </CurrencyDe" +
            "nomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>50 BANI</DenomName>\r" +
            "\n        <DenomValue>0.5</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <Curr" +
            "encyDenomAmount>\r\n        <DenomName>10 BANI</DenomName>\r\n        <DenomValue>0." +
            "1</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n     " +
            "   <DenomName>5 BANI</DenomName>\r\n        <DenomValue>0.05</DenomValue>\r\n      <" +
            "/CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>1 BAN</De" +
            "nomName>\r\n        <DenomValue>0.01</DenomValue>\r\n      </CurrencyDenomAmount>\r\n " +
            "   </DenomAmounts>\r\n  </Currency>\r\n  <Currency>\r\n    <Name>GBP</Name>\r\n    <Desc" +
            "ription>GBP - Lira sterlină</Description>\r\n    <DenomAmounts>\r\n      <CurrencyDe" +
            "nomAmount>\r\n        <DenomName>50 GBP</DenomName>\r\n        <DenomValue>100</Deno" +
            "mValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <Den" +
            "omName>20 GBP</DenomName>\r\n        <DenomValue>50</DenomValue>\r\n      </Currency" +
            "DenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>10 GBP</DenomName>" +
            "\r\n        <DenomValue>20</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <Curr" +
            "encyDenomAmount>\r\n        <DenomName>5 GPB</DenomName>\r\n        <DenomValue>5</D" +
            "enomValue>\r\n      </CurrencyDenomAmount>\r\n    </DenomAmounts>\r\n  </Currency>\r\n  " +
            "<Currency>\r\n    <Name>USD</Name>\r\n    <Description>USD - Dolar american</Descrip" +
            "tion>\r\n    <DenomAmounts>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>100 U" +
            "SD</DenomName>\r\n        <DenomValue>100</DenomValue>\r\n      </CurrencyDenomAmoun" +
            "t>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>50 USD</DenomName>\r\n        " +
            "<DenomValue>50</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomA" +
            "mount>\r\n        <DenomName>20 USD</DenomName>\r\n        <DenomValue>20</DenomValu" +
            "e>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomNam" +
            "e>10 USD</DenomName>\r\n        <DenomValue>10</DenomValue>\r\n      </CurrencyDenom" +
            "Amount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>5 USD</DenomName>\r\n    " +
            "    <DenomValue>5</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDen" +
            "omAmount>\r\n        <DenomName>2 USD</DenomName>\r\n        <DenomValue>2</DenomVal" +
            "ue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomNa" +
            "me>1 USD</DenomName>\r\n        <DenomValue>1</DenomValue>\r\n      </CurrencyDenomA" +
            "mount>\r\n    </DenomAmounts>\r\n  </Currency>\r\n  <Currency>\r\n    <Name>CAD</Name>\r\n" +
            "    <Description>CAD - Dolar canadian</Description>\r\n    <DenomAmounts>\r\n      <" +
            "CurrencyDenomAmount>\r\n        <DenomName>100 CAD</DenomName>\r\n        <DenomValu" +
            "e>100</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n " +
            "       <DenomName>50 CAD</DenomName>\r\n        <DenomValue>50</DenomValue>\r\n     " +
            " </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>20 CAD<" +
            "/DenomName>\r\n        <DenomValue>20</DenomValue>\r\n      </CurrencyDenomAmount>\r\n" +
            "      <CurrencyDenomAmount>\r\n        <DenomName>10 CAD</DenomName>\r\n        <Den" +
            "omValue>10</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmoun" +
            "t>\r\n        <DenomName>5 CAD</DenomName>\r\n        <DenomValue>5</DenomValue>\r\n  " +
            "    </CurrencyDenomAmount>\r\n    </DenomAmounts>\r\n  </Currency>\r\n  <Currency>\r\n  " +
            "  <Name>EUR</Name>\r\n    <Description>EUR - Euro</Description>\r\n    <DenomAmounts" +
            ">\r\n      <CurrencyDenomAmount>\r\n        <DenomName>500 EUR</DenomName>\r\n        " +
            "<DenomValue>500</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenom" +
            "Amount>\r\n        <DenomName>200 EUR</DenomName>\r\n        <DenomValue>200</DenomV" +
            "alue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <Denom" +
            "Name>100 EUR</DenomName>\r\n        <DenomValue>100</DenomValue>\r\n      </Currency" +
            "DenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>50 EUR</DenomName>" +
            "\r\n        <DenomValue>50</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <Curr" +
            "encyDenomAmount>\r\n        <DenomName>20 EUR</DenomName>\r\n        <DenomValue>20<" +
            "/DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n       " +
            " <DenomName>10 EUR</DenomName>\r\n        <DenomValue>10</DenomValue>\r\n      </Cur" +
            "rencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>5 EUR</DenomN" +
            "ame>\r\n        <DenomValue>5</DenomValue>\r\n      </CurrencyDenomAmount>\r\n    </De" +
            "nomAmounts>\r\n  </Currency>\r\n  <Currency>\r\n    <Name>CHF</Name>\r\n    <Description" +
            ">CHF - Franc elvețian</Description>\r\n    <DenomAmounts>\r\n      <CurrencyDenomAmo" +
            "unt>\r\n        <DenomName>1000 CHF</DenomName>\r\n        <DenomValue>1000</DenomVa" +
            "lue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomN" +
            "ame>200 CHF</DenomName>\r\n        <DenomValue>200</DenomValue>\r\n      </CurrencyD" +
            "enomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>100 CHF</DenomName>" +
            "\r\n        <DenomValue>100</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <Cur" +
            "rencyDenomAmount>\r\n        <DenomName>50 CHF</DenomName>\r\n        <DenomValue>50" +
            "</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n      " +
            "  <DenomName>20 CHF</DenomName>\r\n        <DenomValue>20</DenomValue>\r\n      </Cu" +
            "rrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>10 CHF</Deno" +
            "mName>\r\n        <DenomValue>10</DenomValue>\r\n      </CurrencyDenomAmount>\r\n    <" +
            "/DenomAmounts>\r\n  </Currency>\r\n  <Currency>\r\n    <Name>BGN</Name>\r\n    <Descript" +
            "ion>BGN - Leva bulgărească</Description>\r\n    <DenomAmounts>\r\n      <CurrencyDen" +
            "omAmount>\r\n        <DenomName>100 BGN</DenomName>\r\n        <DenomValue>100</Deno" +
            "mValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <Den" +
            "omName>50 BGN</DenomName>\r\n        <DenomValue>50</DenomValue>\r\n      </Currency" +
            "DenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>20 BGN</DenomName>" +
            "\r\n        <DenomValue>20</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <Curr" +
            "encyDenomAmount>\r\n        <DenomName>10 BGN</DenomName>\r\n        <DenomValue>10<" +
            "/DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n       " +
            " <DenomName>5 BGN</DenomName>\r\n        <DenomValue>5</DenomValue>\r\n      </Curre" +
            "ncyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>2 BGN</DenomNam" +
            "e>\r\n        <DenomValue>2</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <Cur" +
            "rencyDenomAmount>\r\n        <DenomName>1 BGN</DenomName>\r\n        <DenomValue>1</" +
            "DenomValue>\r\n      </CurrencyDenomAmount>\r\n    </DenomAmounts>\r\n  </Currency>\r\n " +
            " <Currency>\r\n    <Name>SEK</Name>\r\n    <Description>SEK - Coroana suedeză</Descr" +
            "iption>\r\n    <DenomAmounts>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>100" +
            "0 kr</DenomName>\r\n        <DenomValue>1000</DenomValue>\r\n      </CurrencyDenomAm" +
            "ount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>500 kr</DenomName>\r\n     " +
            "   <DenomValue>500</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDe" +
            "nomAmount>\r\n        <DenomName>100 kr</DenomName>\r\n        <DenomValue>100</Deno" +
            "mValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <Den" +
            "omName>50 kr</DenomName>\r\n        <DenomValue>50</DenomValue>\r\n      </CurrencyD" +
            "enomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>20 kr</DenomName>\r\n" +
            "        <DenomValue>20</DenomValue>\r\n      </CurrencyDenomAmount>\r\n    </DenomAm" +
            "ounts>\r\n  </Currency>\r\n  <Currency>\r\n    <Name>AUD</Name>\r\n    <Description>AUD " +
            "- Dolar australian</Description>\r\n    <DenomAmounts>\r\n      <CurrencyDenomAmount" +
            ">\r\n        <DenomName>100 A$</DenomName>\r\n        <DenomValue>100</DenomValue>\r\n" +
            "      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>50" +
            " A$</DenomName>\r\n        <DenomValue>50</DenomValue>\r\n      </CurrencyDenomAmoun" +
            "t>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>20 A$</DenomName>\r\n        <" +
            "DenomValue>20</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAm" +
            "ount>\r\n        <DenomName>10 A$</DenomName>\r\n        <DenomValue>10</DenomValue>" +
            "\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>" +
            "5 A$</DenomName>\r\n        <DenomValue>5</DenomValue>\r\n      </CurrencyDenomAmoun" +
            "t>\r\n    </DenomAmounts>\r\n  </Currency>\r\n  <Currency>\r\n    <Name>NOK</Name>\r\n    " +
            "<Description>NOK - Coroana norvegiană</Description>\r\n    <DenomAmounts>\r\n      <" +
            "CurrencyDenomAmount>\r\n        <DenomName>1000 kr</DenomName>\r\n        <DenomValu" +
            "e>1000</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n" +
            "        <DenomName>500 kr</DenomName>\r\n        <DenomValue>500</DenomValue>\r\n   " +
            "   </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>200 k" +
            "r</DenomName>\r\n        <DenomValue>200</DenomValue>\r\n      </CurrencyDenomAmount" +
            ">\r\n      <CurrencyDenomAmount>\r\n        <DenomName>100 kr</DenomName>\r\n        <" +
            "DenomValue>100</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomA" +
            "mount>\r\n        <DenomName>50 kr</DenomName>\r\n        <DenomValue>50</DenomValue" +
            ">\r\n      </CurrencyDenomAmount>\r\n    </DenomAmounts>\r\n  </Currency>\r\n  <Currency" +
            ">\r\n    <Name>DKK</Name>\r\n    <Description>DKK - Coroana daneză</Description>\r\n  " +
            "  <DenomAmounts>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>1000 kr</Denom" +
            "Name>\r\n        <DenomValue>1000</DenomValue>\r\n      </CurrencyDenomAmount>\r\n    " +
            "  <CurrencyDenomAmount>\r\n        <DenomName>500 kr</DenomName>\r\n        <DenomVa" +
            "lue>500</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r" +
            "\n        <DenomName>200 kr</DenomName>\r\n        <DenomValue>200</DenomValue>\r\n  " +
            "    </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>100 " +
            "kr</DenomName>\r\n        <DenomValue>100</DenomValue>\r\n      </CurrencyDenomAmoun" +
            "t>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>50 kr</DenomName>\r\n        <" +
            "DenomValue>50</DenomValue>\r\n      </CurrencyDenomAmount>\r\n    </DenomAmounts>\r\n " +
            " </Currency>\r\n  <Currency>\r\n    <Name>CZK</Name>\r\n    <Description>CZK - Coroana" +
            " cehă</Description>\r\n    <DenomAmounts>\r\n      <CurrencyDenomAmount>\r\n        <D" +
            "enomName>5000 kc</DenomName>\r\n        <DenomValue>5000</DenomValue>\r\n      </Cur" +
            "rencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>2000 kc</Deno" +
            "mName>\r\n        <DenomValue>2000</DenomValue>\r\n      </CurrencyDenomAmount>\r\n   " +
            "   <CurrencyDenomAmount>\r\n        <DenomName>1000 kc</DenomName>\r\n        <Denom" +
            "Value>1000</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmoun" +
            "t>\r\n        <DenomName>500 kc</DenomName>\r\n        <DenomValue>500</DenomValue>\r" +
            "\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>2" +
            "00 kc</DenomName>\r\n        <DenomValue>200</DenomValue>\r\n      </CurrencyDenomAm" +
            "ount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>100 kc</DenomName>\r\n     " +
            "   <DenomValue>100</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDe" +
            "nomAmount>\r\n        <DenomName>50 kc</DenomName>\r\n        <DenomValue>50</DenomV" +
            "alue>\r\n      </CurrencyDenomAmount>\r\n    </DenomAmounts>\r\n  </Currency>\r\n  <Curr" +
            "ency>\r\n    <Name>PLN</Name>\r\n    <Description>PLN - Zlot polonez</Description>\r\n" +
            "    <DenomAmounts>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>200 zl</Deno" +
            "mName>\r\n        <DenomValue>200</DenomValue>\r\n      </CurrencyDenomAmount>\r\n    " +
            "  <CurrencyDenomAmount>\r\n        <DenomName>100 zl</DenomName>\r\n        <DenomVa" +
            "lue>100</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r" +
            "\n        <DenomName>50 zl</DenomName>\r\n        <DenomValue>50</DenomValue>\r\n    " +
            "  </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>20 zl<" +
            "/DenomName>\r\n        <DenomValue>20</DenomValue>\r\n      </CurrencyDenomAmount>\r\n" +
            "      <CurrencyDenomAmount>\r\n        <DenomName>10 zl</DenomName>\r\n        <Deno" +
            "mValue>10</DenomValue>\r\n      </CurrencyDenomAmount>\r\n    </DenomAmounts>\r\n  </C" +
            "urrency>\r\n  <Currency>\r\n    <Name>TRY</Name>\r\n    <Description>TRY - Lira turcea" +
            "scă</Description>\r\n    <DenomAmounts>\r\n      <CurrencyDenomAmount>\r\n        <Den" +
            "omName>200 TRY</DenomName>\r\n        <DenomValue>200</DenomValue>\r\n      </Curren" +
            "cyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>100 TRY</DenomNa" +
            "me>\r\n        <DenomValue>100</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <" +
            "CurrencyDenomAmount>\r\n        <DenomName>50 TRY</DenomName>\r\n        <DenomValue" +
            ">50</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n   " +
            "     <DenomName>20 TRY</DenomName>\r\n        <DenomValue>20</DenomValue>\r\n      <" +
            "/CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>10 TRY</D" +
            "enomName>\r\n        <DenomValue>10</DenomValue>\r\n      </CurrencyDenomAmount>\r\n  " +
            "    <CurrencyDenomAmount>\r\n        <DenomName>5 TRY</DenomName>\r\n        <DenomV" +
            "alue>5</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n" +
            "        <DenomName>1 TRY</DenomName>\r\n        <DenomValue>1</DenomValue>\r\n      " +
            "</CurrencyDenomAmount>\r\n    </DenomAmounts>\r\n  </Currency>\r\n  <Currency>\r\n    <N" +
            "ame>HUF</Name>\r\n    <Description>HUF - Forint maghiar</Description>\r\n    <DenomA" +
            "mounts>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>20000 Ft</DenomName>\r\n " +
            "       <DenomValue>20000</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <Curr" +
            "encyDenomAmount>\r\n        <DenomName>10000 Ft</DenomName>\r\n        <DenomValue>1" +
            "0000</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n  " +
            "      <DenomName>5000 Ft</DenomName>\r\n        <DenomValue>5000</DenomValue>\r\n   " +
            "   </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>2000 " +
            "Ft</DenomName>\r\n        <DenomValue>2000</DenomValue>\r\n      </CurrencyDenomAmou" +
            "nt>\r\n      <CurrencyDenomAmount>\r\n        <DenomName>1000 Ft</DenomName>\r\n      " +
            "  <DenomValue>1000</DenomValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDe" +
            "nomAmount>\r\n        <DenomName>500 Ft</DenomName>\r\n        <DenomValue>500</Deno" +
            "mValue>\r\n      </CurrencyDenomAmount>\r\n      <CurrencyDenomAmount>\r\n        <Den" +
            "omName>200 Ft</DenomName>\r\n        <DenomValue>200</DenomValue>\r\n      </Currenc" +
            "yDenomAmount>\r\n    </DenomAmounts>\r\n  </Currency>\r\n</ArrayOfCurrency>")]
        public global::System.Xml.XmlDocument Currency {
            get {
                return ((global::System.Xml.XmlDocument)(this["Currency"]));
            }
            set {
                this["Currency"] = value;
            }
        }
    }
}
